CREATE OR REPLACE FUNCTION public.run_sql_file

(IN par_s3_bucket TEXT,

IN par_s3_file_path TEXT,

    IN par_s3_region TEXT)

RETURNS VOID

/*SELECT *    

     FROM public.run_sql_file

                    ('<S3_Bucket_Name>',

                         '<S3_Path>/<SQL_File_Name>.sql',

                        '<S3_Region>');*/

AS

$BODY$

DECLARE

var_sql TEXT;

var_output TEXT;

BEGIN

          CREATE TEMP TABLE temp_sql(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code text);

             

          SELECT aws_s3.table_import_from_s3(

          'temp_sql',

          'code',

          '(format text, delimiter ''~'')',

          par_s3_bucket,

          par_s3_file_path,

          par_s3_region ) INTO var_output;

             

          SELECT string_agg(code, CHR(10) ORDER BY id)

          INTO var_sql

          FROM (SELECT id,code

                         FROM temp_sql

                         ORDER BY id) sub;

             

          EXECUTE var_sql;

             

          DROP TABLE IF EXISTS temp_sql;

END;

$BODY$

LANGUAGE plpgsql;

